[theme]
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2025"
textColor = "#FAFAFA"

[server]
# For Streamlit Cloud, enable CORS and XSRF for security
enableCORS = true
enableXsrfProtection = true

[logger]
level = "error"

[browser]
gatherUsageStats = false 